### ISSUE TITLE
acoounts is not defined

### ISSUE THREAD

**Issue by obo182** [dappuniversity/defi_tutorial#8]
ReferenceError: acoounts is not defined
    at module.exports (C:\Users\Kamvret\defi_tutorial\migrations\2_deploy_contracts.js:22:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:73:1)
    at Migration._load (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:55:1)
    at Migration.run (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:171:1)
    at Object.runMigrations (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.runAll (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:114:1)
    at Object.run (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:79:1)
    at runMigrations (C:\Users\Kamvret\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:269:1)
Truffle v5.1.39 (core: 5.1.39)
Node v12.16.2

any solution?

**Comment by obo182** [comment]
x
